### ISSUE TITLE
Html-webpack-plugin peerDependency out of date

### ISSUE THREAD

**Issue by detrohutt** [sagold/handlebars-webpack-plugin#85] opened 2021-04-23 15:36 UTC
Hello, and thanks for this plugin. Html-webpack-plugin is on v5.x now. Would you please update your peerDependency to allow the new versions (assuming it is compatible)? Thanks!

**Comment by chaoticvibe** [comment] 2021-06-17 13:05
Yeah i had the same problem...

**Comment by xavierfoucrier** [comment] 2021-08-05 23:24
Hi everyone,

It's a duplicate of https://github.com/sagold/handlebars-webpack-plugin/issues/78.

**Closed as completed** 2021-08-27 14:57 UTC
